id = "poimandres"
name = "poimandres"
version = "0.0.3"
schema_version = 1
authors = ["mshaugh <max@mshaugh.com>"]
description = "poimandres themes"
repository = "https://github.com/mshaugh/poimandres.zed"
